version: "3"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: dbnsaha
      POSTGRES_PASSWORD: saha2815
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbnsaha"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow:
    build: .
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://dbnsaha:saha2815@localhost:5432/postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
